DELETE https://shi.console.ves.volterra.io/api/config/dns/namespaces/system/dns_zones/f5xc-demo.com
?response_format=GET_RSP_FORMAT_FOR_REPLACE
Authorization: APIToken {{$dotenv F5_XC_DNS_PRIV_APITOKEN}}